# Generated by Django 3.2.9 on 2021-11-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/main/static/logo.png', null=True, upload_to='user/'),
        ),
    ]
